# http://module-build.sourceforge.net/META-spec.html
name:         Verilog-Perl
version:      3.012
version_from: Language.pm
license:      perl
installdirs:  site
requires:
    Pod::Usage:                    0

distribution_type: module
generated_by: hand
