# http://module-build.sourceforge.net/META-spec.html
name:         Verilog-Perl
version:      2.316
version_from: Language.pm
license:      perl
installdirs:  site
requires:

distribution_type: module
generated_by: hand
