# http://module-build.sourceforge.net/META-spec.html
name:         Verilog-Perl
version:      3.211
version_from: Language.pm
license:      perl
installdirs:  site
requires:
    Pod::Usage:                    1
    Data::Dumper:                  1
    Test:                          1
    warnings:                      1

distribution_type: module
generated_by: hand
